//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutMaster.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igrac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igrac()
        {
            this.OmiljeniIgraci = new HashSet<OmiljeniIgraci>();
            this.Ucinak = new HashSet<Ucinak>();
        }
    
        public int IDigraca { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int godiste { get; set; }
        public string pozicija { get; set; }
        public string klub { get; set; }
        public int visina { get; set; }
        public string nacionalnost { get; set; }
        public string youtubeLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OmiljeniIgraci> OmiljeniIgraci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucinak> Ucinak { get; set; }
    }
}
