//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutMaster.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OmiljeniIgraci
    {
        public int IDOmiljenogIgraca { get; set; }
        public int IDKorisnika { get; set; }
        public int IDIgraca { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
