//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutMaster.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScoutMasterEntiteti : DbContext
    {
        public ScoutMasterEntiteti()
            : base("name=ScoutMasterEntiteti")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Igrac> Igrac { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<OmiljeniIgraci> OmiljeniIgraci { get; set; }
        public virtual DbSet<Ucinak> Ucinak { get; set; }
        public virtual DbSet<Utakmica> Utakmica { get; set; }
    }
}
